#pragma once

// AGENT: auto-generated by tools/export_kill_counter_tier_cpp.py — do not edit.

namespace pipela::core::kill_counter {

constexpr int kRankTierCount = 51;

extern const int kRankPoints[kRankTierCount];
extern const char* kRankTitles[kRankTierCount];

}  // namespace pipela::core::kill_counter
