#!/usr/bin/env python3
"""Generate C++ kill-counter tier tables from pipela_core.kill_counter_tier_data."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pipela_core.kill_counter_tier_data import (  # noqa: E402
    KILL_COUNTER_RANK_POINTS,
    KILL_COUNTER_RANK_TITLES,
)

OUT_HPP = ROOT / "cpp" / "src" / "core" / "kill_counter" / "tier_data.generated.hpp"
OUT_CPP = ROOT / "cpp" / "src" / "core" / "kill_counter" / "tier_data.generated.cpp"


def _emit() -> None:
    pts = ", ".join(str(p) for p in KILL_COUNTER_RANK_POINTS)
    titles = ",\n        ".join(f'"{t}"' for t in KILL_COUNTER_RANK_TITLES)
    n = len(KILL_COUNTER_RANK_POINTS)
    hpp = f"""#pragma once

// AGENT: auto-generated by tools/codegen/export_kill_counter_tier_cpp.py — do not edit.

namespace pipela::core::kill_counter {{

constexpr int kRankTierCount = {n};

extern const int kRankPoints[kRankTierCount];
extern const char* kRankTitles[kRankTierCount];

}}  // namespace pipela::core::kill_counter
"""
    cpp = f"""// AGENT: auto-generated by tools/codegen/export_kill_counter_tier_cpp.py — do not edit.

#include "tier_data.generated.hpp"

namespace pipela::core::kill_counter {{

const int kRankPoints[kRankTierCount] = {{ {pts} }};

const char* kRankTitles[kRankTierCount] = {{
        {titles}
}};

}}  // namespace pipela::core::kill_counter
"""
    OUT_HPP.write_text(hpp, encoding="utf-8")
    OUT_CPP.write_text(cpp, encoding="utf-8")
    print(f"Wrote {OUT_HPP.name}, {OUT_CPP.name} ({n} tiers)")


if __name__ == "__main__":
    _emit()
